# Workflow for building and deploying documentation to GitHub Pages
name: Deploy Documentation with Jekyll

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Debug step to see repository structure
      - name: Debug - List repository structure
        run: find . -type f -name "README_*.md" | sort
        
      # Copy README files to docs directory with corrected path
      - name: Prepare documentation files
        run: |
          mkdir -p docs/data-system
          # Try multiple possible paths to find the files
          if [ -d "Assets/Scripts/V2/Data/DB" ]; then
            cp -f Assets/Scripts/V2/Data/DB/README_*.md docs/data-system/ || echo "Files not found in Assets/Scripts/V2/Data/DB"
          elif [ -d "assets/scripts/v2/data/db" ]; then
            cp -f assets/scripts/v2/data/db/README_*.md docs/data-system/ || echo "Files not found in lowercase path"
          else
            echo "Searching for README files..."
            find . -name "README_*.md" -exec cp {} docs/data-system/ \; || echo "No README files found"
          fi
          ls -la docs/data-system/
          
      # Setup and build with Jekyll
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4